// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetActiveDataset():Promise<string>;

export function GetAvailableDatasets():Promise<Array<main.DatasetAnalysis>>;

export function GetResults(arg1:number):Promise<Array<main.CustomerResult>>;

export function GetStats():Promise<main.DashboardStats>;

export function GetTrainingHistory():Promise<Array<main.TrainingRecord>>;

export function SelectDataset():Promise<string>;

export function SetActiveDataset(arg1:string):Promise<void>;

export function SetOracleModifier(arg1:number):Promise<void>;

export function StartAnalysis():Promise<void>;

export function TriggerTraining(arg1:number):Promise<void>;

export function UploadDataset(arg1:string):Promise<void>;
