// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetActiveDataset() {
  return window['go']['main']['App']['GetActiveDataset']();
}

export function GetAvailableDatasets() {
  return window['go']['main']['App']['GetAvailableDatasets']();
}

export function GetResults(arg1) {
  return window['go']['main']['App']['GetResults'](arg1);
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetTrainingHistory() {
  return window['go']['main']['App']['GetTrainingHistory']();
}

export function SelectDataset() {
  return window['go']['main']['App']['SelectDataset']();
}

export function SetActiveDataset(arg1) {
  return window['go']['main']['App']['SetActiveDataset'](arg1);
}

export function SetOracleModifier(arg1) {
  return window['go']['main']['App']['SetOracleModifier'](arg1);
}

export function StartAnalysis() {
  return window['go']['main']['App']['StartAnalysis']();
}

export function TriggerTraining(arg1) {
  return window['go']['main']['App']['TriggerTraining'](arg1);
}

export function UploadDataset(arg1) {
  return window['go']['main']['App']['UploadDataset'](arg1);
}
